version: '3.8'

services:
  server:
    build: 
      context: ./server
      args:
        USE_CUDA: "true"  # Enable CUDA support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "5000:5000"
    volumes:
      - ./weights:/app/weights
    environment:
      - FLASK_ENV=production
      - CUDA_VISIBLE_DEVICES=0

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000 